// Generated source fragment. Edit this file, then run npm run build:client.
			//#region 主题样式（全部跟随宿主 --dsw-alias-* 变量，亮/暗自动）
			const S = {
				mButton: { display: "inline-flex", alignItems: "center", gap: "4px", padding: "0 8px", height: "22px", background: "var(--dsw-alias-fill-tsp-secondary)", color: "var(--dsw-alias-label-secondary)", border: "none", borderRadius: "6px", cursor: "pointer", font: "inherit", fontSize: "12px", whiteSpace: "nowrap" },
				panelHost: { position: "fixed", top: 0, right: 0, bottom: 0, left: 0, pointerEvents: "none", zIndex: 40 },
				overlayRoot: { position: "absolute", top: 0, right: 0, bottom: 0, display: "flex", flexDirection: "column", background: "var(--dsw-alias-bg-base)", color: "var(--dsw-alias-label-primary)", fontSize: "13px", minWidth: 0, borderLeft: "1px solid var(--dsw-alias-border-l2)", boxShadow: "-8px 0 24px rgba(16,24,40,0.10)", pointerEvents: "auto" },
				overlayHandle: { position: "absolute", left: -4, top: 0, bottom: 0, width: 8, cursor: "col-resize", zIndex: 1 },
				header: { padding: "10px 14px", borderBottom: "1px solid var(--dsw-alias-border-l2)", flex: "none", display: "flex", flexDirection: "column", gap: "8px" },
				headerTitle: { fontSize: "13px", fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase", color: "var(--dsw-alias-label-secondary)", margin: "0 0 2px 0" },
				metricsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "6px 12px", fontSize: "12px", lineHeight: 1.4, minWidth: 0 },
				metricCell: { display: "flex", flexDirection: "column", gap: "1px", minWidth: 0 },
				metricLabel: { color: "var(--dsw-alias-label-tertiary)", fontSize: "10px", letterSpacing: "0.04em", textTransform: "uppercase", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
				metricValue: { fontWeight: 600, whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums" },
				metricSub: { color: "var(--dsw-alias-label-tertiary)", fontSize: "10px", whiteSpace: "nowrap" },
				gapRow: { display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: "11px", color: "var(--dsw-alias-label-tertiary)", marginTop: "2px" },
				chartWrap: { padding: "10px 14px", borderBottom: "1px solid var(--dsw-alias-border-l2)", flex: "none" },
				chartHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "4px", fontSize: "11px", color: "var(--dsw-alias-label-tertiary)" },
				chartLegend: { display: "flex", gap: "10px", fontSize: "11px" },
				legendItem: { display: "inline-flex", alignItems: "center", gap: "4px" },
				legendDot: { width: "8px", height: "8px", borderRadius: "50%", flex: "none" },
				legendLabel: { color: "var(--dsw-alias-label-secondary)", fontVariantNumeric: "tabular-nums" },
				chartSvg: { display: "block", width: "100%", height: "auto" },
				recentWrap: { flex: "1 1 auto", minHeight: 0, overflow: "auto", padding: "8px 0" },
				recentHeader: { padding: "0 14px 6px", fontSize: "11px", fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase", color: "var(--dsw-alias-label-tertiary)" },
				recentItem: { padding: "6px 14px", cursor: "pointer", transition: "background 0.08s ease", borderBottom: "1px solid var(--dsw-alias-border-l2)" },
				recentItemHover: { background: "var(--dsw-alias-interactive-bg-hover)" },
				recentTop: { display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "8px" },
				recentTime: { flex: "none", fontSize: "11px", fontVariantNumeric: "tabular-nums", color: "var(--dsw-alias-label-tertiary)" },
				recentSummary: { flex: "1 1 auto", minWidth: 0, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", fontWeight: 500 },
				recentMetrics: { display: "flex", gap: "8px", fontSize: "10px", color: "var(--dsw-alias-label-tertiary)", marginTop: "2px", fontVariantNumeric: "tabular-nums" },
				recentMetricChip: { whiteSpace: "nowrap" },
				detailWrap: { padding: "14px", display: "flex", flexDirection: "column", gap: "8px" },
				detailBack: { border: "none", background: "none", cursor: "pointer", font: "inherit", fontSize: "12px", color: "var(--dsw-alias-state-business-primary)", padding: "0", marginBottom: "4px" },
				detailSummary: { fontSize: "14px", fontWeight: 600, lineHeight: 1.4, margin: "0" },
				detailRaw: { fontSize: "12px", lineHeight: 1.6, color: "var(--dsw-alias-label-secondary)", margin: "0", padding: "8px 10px", background: "var(--dsw-alias-fill-tsp-secondary)", borderRadius: "8px", whiteSpace: "pre-wrap", overflowWrap: "anywhere" },
				detailRow: { display: "flex", justifyContent: "space-between", fontSize: "12px", gap: "8px", minHeight: "22px" },
				detailLabel: { color: "var(--dsw-alias-label-tertiary)", flex: "none" },
				detailValue: { fontWeight: 500, textAlign: "right", minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
				detailReason: { fontSize: "11px", lineHeight: 1.5, color: "var(--dsw-alias-label-tertiary)", margin: "2px 0 0", padding: "6px 10px", background: "var(--dsw-alias-fill-tsp-secondary)", borderRadius: "6px" },
				detailTags: { display: "flex", flexWrap: "wrap", gap: "4px" },
				detailTag: { fontSize: "10px", padding: "2px 8px", borderRadius: "6px", background: "var(--dsw-alias-fill-tsp-secondary)", color: "var(--dsw-alias-label-secondary)" },
				emptyWrap: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "8px", height: "100%", padding: "32px 16px", textAlign: "center" },
				emptyIcon: { fontSize: "28px", lineHeight: 1, opacity: 0.5 },
				emptyTitle: { fontSize: "14px", fontWeight: 600, color: "var(--dsw-alias-label-primary)", margin: "0" },
				emptyHint: { fontSize: "12px", color: "var(--dsw-alias-label-tertiary)", margin: "0", lineHeight: 1.5 },
				loadingWrap: { display: "flex", alignItems: "center", justifyContent: "center", height: "100%", color: "var(--dsw-alias-label-tertiary)", fontSize: "13px" },
				refreshBtn: { border: "none", background: "none", cursor: "pointer", font: "inherit", fontSize: "11px", color: "var(--dsw-alias-label-tertiary)", padding: "2px 6px", borderRadius: "4px", lineHeight: 1 },
				refreshBtnHover: { color: "var(--dsw-alias-label-primary)", background: "var(--dsw-alias-interactive-bg-hover)" },
				footer: { padding: "6px 14px", borderTop: "1px solid var(--dsw-alias-border-l2)", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: "10px", color: "var(--dsw-alias-label-caption)", flex: "none" },
			};
			//#endregion
